---
- name: Set OS-specific variables for {{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "vars/{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        # This is to allow to distinguish between Windows-Server/Windows-Client
        - "{{ ansible_os_family }}-{{ ansible_facts.os_installation_type }}"
        - "vars/{{ ansible_os_family }}.yml"
        - "vars/{{ ansible_system }}.yml"
      skip: true
  tags: vars

- name: Compact VM disk image
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_virtualization_type }}_{{ ansible_os_family }}-{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_virtualization_type }}_{{ ansible_os_family }}-{{ ansible_distribution }}.yml"
        # This is to allow to distinguish between Windows-Server/Windows-Client
        - "{{ ansible_os_family }}-{{ ansible_facts.os_installation_type }}"
        - "{{ ansible_virtualization_type }}_{{ ansible_os_family }}.yml"
        - "{{ ansible_virtualization_type }}_{{ ansible_system }}.yml"
