---
- name: Remove unnecessary packages
  ansible.builtin.include_tasks: Linux/RedHat-remove_packages.yaml

- name: Remove or wipe unnecessary files
  ansible.builtin.include_tasks: Linux/RedHat-wipe_files.yaml

- name: Zero out empty space
  ansible.builtin.include_tasks: Linux/zerofree.yaml
  vars:
    zerofree_path: "{{ path }}"
  loop:
    - "/"
    - "/boot"
  loop_control:
    loop_var: path

- name: Zero out swap space
  ansible.builtin.shell: |
    swappart="$(readlink -f /dev/disk/by-uuid/$swapuuid)";
    /sbin/swapoff "$swappart";
    dd if=/dev/zero of="$swappart" bs=1M || echo "dd exit code $? is suppressed";
    /sbin/mkswap -U "$swapuuid" "$swappart";
