---
- name: Take ownership of {{ path }}
  when: ansible_os_family == "Windows"
  ansible.windows.win_shell: |
    if (Test-Path {{ path }}) {
      takeown.exe /D Y /R /F {{ path }}
    }

- name: Set filesystem permissions for {{ path }}
  when: ansible_os_family == "Windows"
  ansible.windows.win_shell: |
    if (Test-Path {{ path }}) {
      icacls.exe {{ path }} /grant:r Administrators:F /T /C /Q
    }

- name: Kill OneDrive processes if present
  ansible.windows.win_shell: |
    if (Get-Process -Name "OneDrive") { Stop-Process -Name "OneDrive" -Force }

- name: Kill Explorer process
  ansible.windows.win_shell: |
    Stop-Process -Name "explorer" -Force

- name: Remove {{ path }}
  when: ansible_os_family == "Windows"
  ansible.windows.win_shell: |
    if (Test-Path {{ path }}) {
      Remove-Item {{ path }} -Exclude 'packer-*','vmware-*' -Recurse -Force -ErrorAction SilentlyContinue
    }
  retries: 3
  delay: 5
  register: removed
  until: removed is not failed

- name: Restart Explorer
  ansible.windows.win_shell: Start-Process explorer.exe
