---
- name: Find all files in `/var/log`
  ansible.builtin.find:
    path: /var/log
    type: file
  register: log_files

- name: Zero out all log files
  ansible.builtin.shell: truncate --size=0 {{ logfile.path }}
  become: true
  loop: "{{ log_files }}"
  loop_control:
    loop_var: logfile
