---
- name: Remove dependencies that are no longer required and purge their configuration files
  ansible.builtin.apt:
    autoremove: yes
    purge: true
  become: true

- name: Run apt-clean
  ansible.builtin.apt:
    clean: yes
  become: true

- name: Clear up unnecessary data # noqa: no-changed-when
  ansible.builtin.shell: |
    find /var/log -type f -exec truncate --size=0 {} \;
    rm -rf /tmp/* /var/tmp/*
    rm -f /root/.wget-hsts
  become: true

- name: Cleaning the machine-id.
  block:
    - name: Emptying the /etc/machine-id.
      community.general.filesize:
        path: /etc/machine-id
        size: 0
    - name: Removing /var/lib/dbus/machine-id.
      ansible.builtin.file:
        path: /var/lib/dbus/machine-id
        state: absent
    - name: Creating a symbolic link to /etc/machine-id.
      ansible.builtin.file:
        src: /etc/machine-id
        dest: /var/lib/dbus/machine-id
        state: link
  become: true

- name: Cleaning the shell history.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.bash_history"
    state: absent