---
# We need to ignore errors here because dd will error out when it runs out of disk space
- name: Zero out free space in {{ zerofree_path }}  # noqa:no-changed-when
  ignore_errors: true   # noqa: ignore-errors
  ansible.builtin.shell: |
    dd if=/dev/null of={{ zerofree_path }}/nullfile
    rm {{ zerofree_path }}/nullfile
  become: true
